@startuml
package "controller" {
    Class ExceptionController
    Class PurchaseController
    Class SaleController
    Class Settings
}

package "dal" {
    Class DataStore
    Interface IDataMapper
    Interface IDataStore
    Class TextDataStore
}

package "model" {
    Class Cart
    Class Customer
    Class Product
}

package "view" {
    Console <-- IUserView
    Class Display
    Class IUserView
}
@enduml